# Shutdown URL for debug
GET http://localhost:8080/debug/application/ktor/shutdown

###
#Register User
POST http://api.2222.reiwa.app/api/user/register
Content-Type: application/json

{
  "name": "toliner",
  "mail": "test+2222@toliner.dev"
}

###

# Verify User
GET http://api.2222.reiwa.app/api/user/verification?token=410cf04e-535a-4b56-b07d-32943294c696

###
