name: Run Gradle test on PRs and Pushes
on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@v1
        with:
          path: "~/.gradle/caches"
          key: gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: gradle-

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: run test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
          build-root-directory: backend
          wrapper-directory: backend

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: test-result
          path: backend/build/reports/tests
